// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// calc_tfce_cpp
NumericVector calc_tfce_cpp(NumericVector t_stat, IntegerVector dims, double E, double H, double dh, int connectivity);
RcppExport SEXP _WMskelstats_calc_tfce_cpp(SEXP t_statSEXP, SEXP dimsSEXP, SEXP ESEXP, SEXP HSEXP, SEXP dhSEXP, SEXP connectivitySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type t_stat(t_statSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type dims(dimsSEXP);
    Rcpp::traits::input_parameter< double >::type E(ESEXP);
    Rcpp::traits::input_parameter< double >::type H(HSEXP);
    Rcpp::traits::input_parameter< double >::type dh(dhSEXP);
    Rcpp::traits::input_parameter< int >::type connectivity(connectivitySEXP);
    rcpp_result_gen = Rcpp::wrap(calc_tfce_cpp(t_stat, dims, E, H, dh, connectivity));
    return rcpp_result_gen;
END_RCPP
}
// fast_rint_reg_multi_y_cpp
Rcpp::List fast_rint_reg_multi_y_cpp(const arma::mat& Y, const arma::mat& X, const arma::uvec& group_offsets, const arma::uvec& group_sizes, double gamma);
RcppExport SEXP _WMskelstats_fast_rint_reg_multi_y_cpp(SEXP YSEXP, SEXP XSEXP, SEXP group_offsetsSEXP, SEXP group_sizesSEXP, SEXP gammaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type Y(YSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::uvec& >::type group_offsets(group_offsetsSEXP);
    Rcpp::traits::input_parameter< const arma::uvec& >::type group_sizes(group_sizesSEXP);
    Rcpp::traits::input_parameter< double >::type gamma(gammaSEXP);
    rcpp_result_gen = Rcpp::wrap(fast_rint_reg_multi_y_cpp(Y, X, group_offsets, group_sizes, gamma));
    return rcpp_result_gen;
END_RCPP
}
// cpp_smooth_voxel_matrix
NumericMatrix cpp_smooth_voxel_matrix(NumericMatrix data_mat, IntegerMatrix coords, NumericVector sigma_voxels);
RcppExport SEXP _WMskelstats_cpp_smooth_voxel_matrix(SEXP data_matSEXP, SEXP coordsSEXP, SEXP sigma_voxelsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type data_mat(data_matSEXP);
    Rcpp::traits::input_parameter< IntegerMatrix >::type coords(coordsSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type sigma_voxels(sigma_voxelsSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_smooth_voxel_matrix(data_mat, coords, sigma_voxels));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_WMskelstats_calc_tfce_cpp", (DL_FUNC) &_WMskelstats_calc_tfce_cpp, 6},
    {"_WMskelstats_fast_rint_reg_multi_y_cpp", (DL_FUNC) &_WMskelstats_fast_rint_reg_multi_y_cpp, 5},
    {"_WMskelstats_cpp_smooth_voxel_matrix", (DL_FUNC) &_WMskelstats_cpp_smooth_voxel_matrix, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_WMskelstats(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
