#' Plot White Matter Skeleton Statistics as a Slice Lightbox
#'
#' @description
#' Visualize voxel-wise white matter skeleton statistics across selected slices
#' perpendicular to one coordinate axis. Each slice is displayed in a separate
#' panel, with points colored according to their voxel-wise values.
#'
#' @param x_slices Numeric vector of slice coordinates along the x-axis.
#'   Specify exactly one of \code{x_slices}, \code{y_slices}, or
#'   \code{z_slices}, leaving the other two arguments unspecified.
#' @param y_slices Numeric vector of slice coordinates along the y-axis.
#' @param z_slices Numeric vector of slice coordinates along the z-axis.
#' @param vox_data Numeric vector of voxel-wise values, such as t-statistics.
#'   Its length must equal the number of rows in \code{coords}, with values
#'   in the same voxel order. Missing values are displayed using
#'   \code{na_color}.
#' @param coords Numeric matrix or data frame with one row per voxel and
#'   x, y, and z coordinates in its first three columns, respectively.
#'   Coordinates must use the same units and reference space as the requested
#'   slice coordinates.
#' @param pointsize Numeric value specifying the point size passed to
#'   \code{ggplot2::geom_point()}. Defaults to \code{1}.
#' @param strip_fontsize Numeric value specifying the font size of the strip passed to
#'   \code{ggplot2::element_text()}. Defaults to \code{10}.
#' @param strip_margin Numeric value specifying the bottom margin of the
#'   slice labels, in points. Defaults to \code{5}.
#' @param cmap Character string specifying the color palette. Supported values
#'   are \code{"viridis"}, \code{"plasma"}, \code{"inferno"}, \code{"magma"},
#'   \code{"cividis"}, \code{"jet"}, \code{"rainbow"}, and \code{"hot"}.
#'   Defaults to \code{"viridis"}. Unrecognized values use the
#'   \code{"viridis"} palette.
#' @param colorscale_title Character string specifying the color legend title.
#'   Defaults to \code{"t-stat"}.
#' @param dark_mode Logical; whether to use a black plot background with white
#'   slice labels and legend text. Defaults to \code{FALSE}.
#' @param nrow Positive integer specifying the number of rows in the faceted
#'   layout. Defaults to \code{1}.
#' @param na_color Character string specifying the color used for missing
#'   values in \code{vox_data}. Defaults to \code{"#7F7F7F"}.
#'
#' @details
#' Slice selection uses exact matching against the corresponding column of
#' \code{coords}; no interpolation, rounding, or spatial transformation is
#' performed. Requested slices without matching voxels are omitted. At least
#' one requested slice must contain voxels.
#'
#' For x-axis slices, the horizontal and vertical plotting coordinates are
#' y and z; for y-axis slices, they are x and z; and for z-axis slices, they
#' are x and y. Coordinates are plotted as supplied, without axis reversal
#' or anatomical orientation correction.
#'
#' Panels use a fixed coordinate aspect ratio of one and share a continuous
#' color scale determined by the values in the selected slices. The color
#' scale is not automatically centered on zero. Slice labels are character
#' strings, so panel order follows the default ordering of
#' \code{ggplot2::facet_wrap()}, rather than the order of the supplied slices.
#'
#' Palettes are generated by \code{get_palette_colors()} using interpolation
#' between predefined colors.
#'
#' @return
#' A \code{ggplot} object. The plot is also printed when the function is called.
#'
#' @examples
#' # Illustrative voxel coordinates and statistics
#' coords <- as.matrix(expand.grid(
#'   x = 1:5,
#'   y = 1:5,
#'   z = c(10, 20, 30)
#' ))
#' vox_data <- seq(-3, 3, length.out = nrow(coords))
#'
#' # Display three z-axis slices
#' p <- plot_lightbox(
#'   z_slices = c(10, 20, 30),
#'   vox_data = vox_data,
#'   coords = coords,
#'   colorscale_title = "t-stat"
#' )
#'
#' # Display y-axis slices with a dark background
#' p_dark <- plot_lightbox(
#'   y_slices = c(2, 4),
#'   vox_data = vox_data,
#'   coords = coords,
#'   cmap = "inferno",
#'   dark_mode = TRUE,
#'   nrow = 2
#' )
#'
#' @importFrom ggplot2 ggplot aes geom_point coord_fixed scale_color_gradientn
#' @importFrom ggplot2 facet_wrap theme_void theme element_rect element_text
#' @importFrom ggplot2 margin element_line
#' @importFrom grid unit
#' @importFrom grDevices colorRampPalette rainbow
#' @export

plot_lightbox=function(x_slices,
                       y_slices,
                       z_slices,
                       vox_data, 
                       coords,
                       pointsize=1, 
                       strip_fontsize=10,
                       strip_margin=5,
                       cmap="viridis", 
                       colorscale_title="t-stat",
                       dark_mode=FALSE,
                       nrow=1,
                       na_color="#7F7F7F")
{
  cmap.dat=get_palette_colors(cmap)
  if(dark_mode==T)
  {
    bg_color="black"
    title_color="white"
  } else if(dark_mode==F)
  {
    bg_color="white"
    title_color="black"
  }
  
  #check if more than one of the axes is specified
  n_supplied=sum(!missing(x_slices), !missing(y_slices), !missing(z_slices))
  if (n_supplied != 1) {stop("Only one of `x_slices`, `y_slices`, or `z_slices` may be specified.")}
  
  #plotting X slices
  if(!missing(x_slices))
  {
    keep.x.idx=which(!is.na(match(coords[,1],x_slices)))
    coords.keep.x=coords[keep.x.idx, ,drop = FALSE]
    dat.keep=vox_data[keep.x.idx]
    
    dat.plot=data.frame(x=coords.keep.x[,1],y=coords.keep.x[,2],z=coords.keep.x[,3], color=dat.keep)
    dat.plot$x=paste0("X=",dat.plot$x)
    
    plot.obj=ggplot(dat.plot,aes(x=y,y=z,color=color))+
      geom_point(size=pointsize)+
      coord_fixed(ratio = 1)+
      scale_color_gradientn(name=colorscale_title,colors = cmap.dat,na.value = na_color)+
      facet_wrap(~x,nrow = nrow)+
      theme_void()+
      theme(strip.text = element_text(margin = margin(b = strip_margin),face ="bold", colour = title_color,size = strip_fontsize),
            plot.background = element_rect(fill = bg_color),
            panel.spacing = unit(0, "lines"),
            panel.spacing.y = unit(0.1, "lines"),
            legend.position = "bottom", 
            legend.title = element_text(color=title_color,face="bold"),
            legend.text = element_text(color=title_color),
            legend.ticks = element_line(colour = bg_color))
  }
  #plotting Y slices
  if(!missing(y_slices))
  {
    keep.y.idx=which(!is.na(match(coords[,2],y_slices)))
    coords.keep.y=coords[keep.y.idx, ,drop = FALSE]
    dat.keep=vox_data[keep.y.idx]
    
    dat.plot=data.frame(x=coords.keep.y[,1],y=coords.keep.y[,2],z=coords.keep.y[,3], color=dat.keep)
    dat.plot$y=paste0("Y=",dat.plot$y)
    
    plot.obj=ggplot(dat.plot,aes(x=x,y=z,color=color))+
      geom_point(size=pointsize)+
      coord_fixed(ratio = 1)+
      scale_color_gradientn(name=colorscale_title,colors = cmap.dat,na.value = na_color)+
      facet_wrap(~y,nrow = nrow)+
      theme_void()+
      theme(strip.text = element_text(margin = margin(b = strip_margin),face ="bold", colour = title_color,size = strip_fontsize),
            plot.background = element_rect(fill = bg_color),
            panel.spacing = unit(0, "lines"),
            panel.spacing.y = unit(0.1, "lines"),
            legend.position = "bottom", 
            legend.title = element_text(color=title_color,face="bold"),
            legend.text = element_text(color=title_color),
            legend.ticks = element_line(colour = bg_color))
  }
  #plotting Z slices
  if(!missing(z_slices))
  {
    keep.z.idx=which(!is.na(match(coords[,3],z_slices)))
    coords.keep.z=coords[keep.z.idx, ,drop = FALSE]
    dat.keep=vox_data[keep.z.idx]
    
    dat.plot=data.frame(x=coords.keep.z[,1],y=coords.keep.z[,2],z=coords.keep.z[,3], color=dat.keep)
    dat.plot$z=paste0("Z=",dat.plot$z)
    
    plot.obj=ggplot(dat.plot,aes(x=x,y=y,color=color))+
      geom_point(size=pointsize)+
      coord_fixed(ratio = 1)+
      scale_color_gradientn(name=colorscale_title,colors = cmap.dat,na.value = na_color)+
      facet_wrap(~z,nrow = nrow)+
      theme_void()+
      theme(strip.text = element_text(margin = margin(b = strip_margin),face ="bold", colour = title_color,size = strip_fontsize),
            plot.background = element_rect(fill = bg_color),
            panel.spacing = unit(0, "lines"),
            panel.spacing.y = unit(0.2, "lines"),
            legend.position = "bottom", 
            legend.title = element_text(color=title_color,face="bold"),
            legend.text = element_text(color=title_color),
            legend.ticks = element_line(colour = bg_color))
  }
  print(plot.obj)
  return(plot.obj)
}
