# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

calc_tfce_cpp <- function(t_stat, dims, E = 0.5, H = 2.0, dh = 0.1, connectivity = 26L) {
    .Call(`_WMskelstats_calc_tfce_cpp`, t_stat, dims, E, H, dh, connectivity)
}

fast_rint_reg_multi_y_cpp <- function(Y, X, group_offsets, group_sizes, gamma = 0.5) {
    .Call(`_WMskelstats_fast_rint_reg_multi_y_cpp`, Y, X, group_offsets, group_sizes, gamma)
}

cpp_smooth_voxel_matrix <- function(data_mat, coords, sigma_voxels) {
    .Call(`_WMskelstats_cpp_smooth_voxel_matrix`, data_mat, coords, sigma_voxels)
}

