# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

calc_tfce_cpp <- function(t_stat, dims, E = 1, H = 2.0, dh = 0.0, connectivity = 26L, tail = 2L) {
    .Call(`_WMskelstats_calc_tfce_cpp`, t_stat, dims, E, H, dh, connectivity, tail)
}

lm_multi_t_cpp <- function(X, Y, block_size = 2048L, tol = 1e-12, return_coefficients = FALSE) {
    .Call(`_WMskelstats_lm_multi_t_cpp`, X, Y, block_size, tol, return_coefficients)
}

fast_rint_reg_multi_y_cpp <- function(Y, X, group_offsets, group_sizes, gamma_max = 1e8, tol = 1e-8, max_iter = 200L, grid_size = 41L) {
    .Call(`_WMskelstats_fast_rint_reg_multi_y_cpp`, Y, X, group_offsets, group_sizes, gamma_max, tol, max_iter, grid_size)
}

cpp_smooth_voxel_matrix <- function(data_mat, coords, sigma_voxels) {
    .Call(`_WMskelstats_cpp_smooth_voxel_matrix`, data_mat, coords, sigma_voxels)
}

