# Run from this archive's extracted directory: Rscript test_transform_lookup.R
source("qsi_find_transform.R")
root <- tempfile("qsi_lookup_")
subid <- "sub-NDARDT550XYX"
ses <- "ses-HBNsiteCUNY"
suffix <- "_from-ACPC_to-MNI152NLin2009cAsym_mode-image_xfm.h5"
anat <- file.path(root, subid, "anat")
ses_anat <- file.path(root, subid, ses, "anat")
other <- file.path(root, subid, "ses-other", "anat")
for (path in c(anat, ses_anat, other)) dir.create(path, recursive=TRUE)
shared <- file.path(anat, paste0(subid, suffix))
file.create(shared)
file.create(file.path(anat, paste0(subid, "_from-MNI152NLin2009cAsym_to-ACPC_mode-image_xfm.h5")))
file.create(file.path(other, paste0(subid, "_ses-other", suffix)))
stopifnot(identical(.qsi_find_transform(root, subid, ses), shared))
local <- file.path(ses_anat, paste0(subid, "_", ses, suffix))
file.create(local)
stopifnot(identical(.qsi_find_transform(root, subid, ses), local))
unlink(local)
unlink(shared)
stopifnot(length(.qsi_find_transform(root, subid, ses)) == 0L)
file.create(shared)
stopifnot(identical(.qsi_find_transform(root, subid), shared))
unlink(root, recursive=TRUE)
message("Transform lookup checks passed")
